### ISSUE TITLE
ocserv 保存密码

### ISSUE THREAD

**Issue by gamerenzz** [chendong12/ocserv#1]
这教程很全，厉害

网上看到的，ocserv 使anyconnect保存密码，

没试过，对go不懂，可以参考，

不知道能否实现anyconnect保存密码后，怎么可以更换用户

https://www.v2ex.com/t/195064#reply6

https://gist.github.com/horsley/e286276f83cae9b60d98

**Comment by chendong12** [comment]
有时间可以研究一下
