### ISSUE TITLE
对接radius中有几个文件失效了！

### ISSUE THREAD

**Issue by wuchangbai888** [chendong12/ocserv#25]
http://180.188.197.212/down/daloradius-0.9-9.tar.gz
http://180.188.197.212/down/radacct_new.sql.tar.gz
http://180.188.197.212/down/daloradius20180418.tar.gz
http://180.188.197.212/down/dbback.tar.gz
都是404，大佬可以解决一下吗

**Comment by chendong12** [comment]
已经更新
